---

TRAIN_CSV_PATH: '/content/drive/MyDrive/Product10k/train.csv'
TEST_CSV_PATH: '/content/drive/MyDrive/Product10k/test.csv'
IMG_PATH: '/content/train/'
TEST_IMG_PATH: '/content/test/'
CHECKPOINT_PATH: '/content/drive/MyDrive/model_checkpoint'
MAP_SCORES_PATH: '/content/drive/MyDrive/'
MODEL_NAME: 'mobilenetv3_large_100'
NUM_CLASSES: 9691   ## 361
EMB_DIM: 768
BATCH_SIZE: 64
NUM_EPOCHS: 10
LR: 0.0001
MODEL_PATH: '/content/drive/MyDrive/model_checkpoint/model_triplet_c&g_LR_imbalance_handled_0.0001_0002.pth'