---
system:
  train_csv_path: ../data/train.csv
  test_csv_path: ../data/test.csv
  train_samples_path: ../data/train/
  test_samples_path: /../../Product10k/test/
  output: ./output
  map_scores_path: /content/drive/MyDrive/
  split_ratio: 0.15
  device: 'cpu'

MobNet:
  model_name: mobilenetv3_large_100
  num_classes: 9691
  embedding_dim: 128
  batch_size: 4
  epochs: 10
  optimizer:
    name: sgd
    lr: 0.0001
    momentum: 0.9
    decay: 0.0001
  loss_fn: 'arc_face'
  sampler: 'group_based'
  load_saved: False
  from_timm: True
  output_dir: /content/drive/MyDrive/model_checkpoint/model_triplet_c&g_LR_imbalance_handled_0.0001_0002.pth

BEiT:
  MODEL_NAME: 'microsoft/beit-base-patch16-224-pt22k'
  num_classes: 9691
  embedding_dim: 726
  batch_size: 64
  epochs: 10
  optimizer:
    name: sgd
    lr: 0.0001
    momentum: 0.9
    decay: 0.0001
  loss_fn: 'arc_face'
  sampler: 'group_based'
  load_saved: False
  from_timm: True
  output_dir: '/content/drive/MyDrive/model_checkpoint/model_triplet_c&g_LR_imbalance_handled_0.0001_0002.pth'

VitB:
  MODEL_NAME: 'ViT-B-32-quickgelu'
  num_classes: 9691
  embedding_dim: 512
  batch_size: 4
  epochs: 10
  optimizer:
    name: sgd
    lr: 0.001
    momentum: 0.9
    decay: 0.0001
  loss_fn: 'cross_entropy'
  sampler: 'group_based'
  load_saved: False
  from_timm: True
  output_dir: '/content/drive/MyDrive/model_checkpoint/model_triplet_c&g_LR_imbalance_handled_0.0001_0002.pth'
